name: Update version

on:
  pull_request:
    branches:
      - feature/*
      - hotfix/*
    types: [closed]

jobs:

  update-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version:
                - 3.x

    steps:
    - uses: actions/checkout@v2

    - name: Update version
      run: python3 tools/update_version.py
      
    - name: Commit & Push
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"                                    
          git add -A && git diff-index --cached --quiet HEAD || git commit -m 'Update version of package'
          git push origin HEAD