name: Update version action

on:
  push:
    branches:
      - feature/*

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version:
                - 3.x

    steps:
    - uses: actions/checkout@v2

    - name: Prerequisite
      run: |
          pip3 install --upgrade pip setuptools

    - name: Udpdate version
      run: python tools/update_version.py
      
    - name: Commit & Push
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"                                    
          git add -A && git diff-index --cached --quiet HEAD || git commit -m 'Update version of package'
          git push